### ISSUE TITLE
formatting issue and go 1.11 behavior

### ISSUE THREAD

**Issue by ivanguravel** [banzaicloud/spot-termination-exporter#10]
Hello! 

I faced with different issues during installation your exporter.

1) seems like go version for promu have different format:
`go:    
    version: 1.11.4`

Example: https://github.com/prometheus/promu/blob/master/.promu.yml#L4

2) i faced with: `go get github.com/prometheus/promu && promu build` -> `-bash: promu: command not found`.

Here is my instcution, how to install:

- install `go`. 
- clone `github.com/prometheus/promu` repo.
- install `cmake` and `gcc`. For example in centos you could run: `sudo yum install cmake gcc -y`
- `cd promu && make`
- `sudo mv promu /usr/local/bin`
- clone `github.com/banzaicloud/spot-termination-exporter` repo.
- change .promu.yml as i described in point `1)`

Environment: `CentOS-7`

If you will enable an access i can send MR with those changes.

Thanks!

**Comment by waynz0r** [comment]
Hi @ivanguravel,

thanks for reporting this! I just created a PR to fix the issue.
